// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    //apiKey: 'AIzaSyBpe6hoDNxawY2A06-82RkBWVqoRB_zvLQ',
    appId: '1:8835503535:android:0d30dca5dab1b2fe5fcb5a',
    messagingSenderId: '8835503535',
    projectId: 'flutter-prep-1b036',
    databaseURL: 'https://flutter-prep-1b036-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-1b036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyBLJJdG7Dc22QLJqWas7N7XFBiV3vggt0I',
    appId: '1:8835503535:ios:a10ba3b95c3541a05fcb5a',
    messagingSenderId: '8835503535',
    projectId: 'flutter-prep-1b036',
    databaseURL: 'https://flutter-prep-1b036-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-1b036.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}